version: '3.8'

services:
  postgres:
    build: ./database
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./volume/psql.data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./server
    container_name: todo-api
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      ENVIRONMENT: development
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  client:
    build: ./client
    container_name: todo-client
    ports:
      - "3000:5173"
    volumes:
      - ./client/src:/app/src
    depends_on:
      - api
    restart: unless-stopped